[font]
normal = { family = "Hack Nerd Font", style = "Normal" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 10.00

[colors.primary]
background = '#EEEEEE'
foreground = '#444444'

[colors.cursor]
text= '#eeeeee'
cursor= '#444444'

[colors.normal]
  black=   '#eeeeee'
    red=     '#af0000'
    green=   '#008700'
    yellow=  '#5f8700'
    blue= '#0087af'
    magenta= '#878787'
    cyan= '#005f87'
    white=   '#444444'

[colors.bright]
 black=   '#bcbcbc'
    red=     '#d70000'
    green=   '#d70087'
    yellow=  '#8700af'
    blue=  '#d75f00'
    magenta= '#d75f00'
    cyan=    '#005faf'
    white=   '#005f87'
